config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :announcements do
    resources :comments
  end
  resources :attendances
  resources :marks
  resources :observations
  resources :students
  resources :parents
  resources :families
  resources :staffs
  resources :schools
  resources :classrooms
  resources :subjects
  resources :activities
  resources :likes
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :activities
      resources :classrooms
      resources :schools
      resources :staffs
      resources :students
    end
  end

  get 'gradebook/:classroom_id', to: 'gradebooks#show_classroom', as: 'gradebook_classroom'
  get 'gradebook', to: 'gradebooks#index', as: 'gradebook'

  get 'user_activities/:id', to: 'user_activities#index', as: 'user_activities'

  get 'staffs/:id/activate', to: 'staffs#activate', as: 'activate_staff'
  get 'staffs/:id/deactivate', to: 'staffs#deactivate', as: 'deactivate_staff'

  get 'students/:id/remove_student_from_classroom/:classroom_id', to: 'students#remove_student_from_classroom', as: 'remove_student_from_classroom'
  get 'transfer_student_to_form', to: 'students#transfer_student_to_form', as: 'transfer_student_to_form'
  get 'add_student_to_optional_classroom', to: 'students#add_student_to_optional_classroom', as: 'add_student_to_optional_classroom'

  get 'staffs/:id/remove_staff_from_classroom/:classroom_id', to: 'staffs#remove_staff_from_classroom', as: 'remove_staff_from_classroom'

  get 'profile', to: 'profile#index', as: 'profile'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/staff.rb
class Staff < ApplicationRecord
	belongs_to :current_school, class_name: :School, foreign_key: :current_school_id

	has_and_belongs_to_many :classrooms
	has_and_belongs_to_many :schools
	
	has_one :form, class_name: :Classroom, foreign_key: :form_tutor
	has_one :user, as: :profile, dependent: :destroy

	has_many :activities, foreign_key: "coordinator_id", dependent: :destroy
	has_many :announcements, foreign_key: "sender_id", dependent: :destroy
	has_many :marks, dependent: :destroy

	accepts_nested_attributes_for :user, update_only: true

	def self.has_school school
		Staff.all.filter {|s| s.schools.include? school}
	end

	def name
		user.name
	end
end

app/controllers/api/v1/staffs_controller.rb
class Api::V1::StaffsController < Api::V1::BaseController
  def index
    if params[:school_id]
      @staffs = Staff.has_school School.find(params[:school_id])
    elsif params[:form_id]
      @staffs = Classroom.find(params[:form_id]).form_tutor
    else
      @staffs = Staff.all
    end

    render :index, formats: :json
  end

  def show
    @staff = Staff.find(params[:id])

    render :show, formats: :json
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  def index
    @search = Staff.reverse_chronologically.ransack(params[:q])

    respond_to do |format|
      format.any(:html, :json) { @staffs = set_page_and_extract_portion_from @search.result }
      format.csv { render csv: @search.result }
    end
  end

  def show
    fresh_when etag: @staff
  end

  def new
    @staff = Staff.new
    @staff.initial_password = Passgen::generate(lowercase: :only, uppercase: false)
  end

  def edit
    @staff = Staff.find(params[:id])
    @user = @staff.user
  end

  def create
    @staff = Staff.new(staff_params)
    @staff.save!
    
    # Try to create user for staff
    begin
      @user = User.new(user_params)
      @user.avatar.attach(params[:user][:avatar])
      @user.save!
    rescue
      @staff.destroy

      respond_to do |format|
        format.html { redirect_to staffs_path, flash: { error: 'Error. Staff could not be created.' } }
        format.json { render :index, status: :failed }
      end
      return
    end

    UserMailer.staff_welcome_email(@user).deliver

    respond_to do |format|
      format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
      format.json { render :show, status: :created }
    end
  end

  def update
    @staff.update!(staff_params)
    @staff.user.avatar.attach(params[:user][:avatar]) if params[:user] && params[:user][:avatar]
    @staff.user.update!(user_params) if params[:user]
    respond_to do |format|
      format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
      format.json { render :show }
      format.js
    end
  end

  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deactivate
    @staff = Staff.find(params[:id])
    @staff.user.update(active: false)
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully deactivated.' }
      format.json { head :no_content }
    end
  end

  def activate
    @staff = Staff.find(params[:id])
    @staff.user.update(active: true)
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully reactivated.' }
      format.json { head :no_content }
    end
  end

  def remove_staff_from_classroom
    @staff = Staff.find(params[:id])
    @classroom = Classroom.find(params[:classroom_id])
    if @classroom.form_tutor == @staff
      return
    elsif @classroom.staffs.include? @staff
      @staff.update! classrooms: @staff.classrooms - [ @classroom ]
    end
    respond_to do |format|
      format.html { redirect_to @classroom, notice: 'Staff was successfully removed from the classroom.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    def set_staff
      @staff = Staff.find(params[:id])
    end

    def staff_params
      params.require(:staff).permit(:initial_password, :current_school_id, user: [ :first_name, :last_name, :gender, :phone, :email, :birth_date, :avatar ])
    end

    def user_params
      {
        first_name: params[:user][:first_name],
        last_name: params[:user][:last_name],
        phone: params[:user][:phone],
        email: params[:user][:email],
        gender: params[:user][:gender],
        password: @staff.initial_password,
        password_confirmation: @staff.initial_password,
        profile: @staff
      }
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, multipart: true, data: { controller: 'validation' }) do |form| %>
	<%= fields_for :user do |f| %>
		<div class="row">
			<!-- First name -->
	    <div class="form-group col-md-6 mb-2">
	      <div class="input-group input-group-merge input-group-alternative mb-3">
	        <div class="input-group-prepend">
	          <span class="input-group-text"><i class="far fa-user"></i></span>
	        </div>
	        <%= f.text_field :first_name, autofocus: true, class: 'form-control', placeholder: :first_name, required: true %>
	      </div>
	    </div>

	    <!-- Last name -->
	    <div class="form-group col-md-6 mb-2">
	      <div class="input-group input-group-merge input-group-alternative mb-3">
	        <div class="input-group-prepend">
	          <span class="input-group-text"><i class="far fa-user"></i></span>
	        </div>
	        <%= f.text_field :last_name, class: 'form-control', placeholder: :last_name, required: true %>
	      </div>
	    </div>
    </div>

    <div class="row">
	    <!-- Phone -->
	    <div class="form-group col-md-6 mb-2">
	      <div class="input-group input-group-merge input-group-alternative mb-3">
	        <div class="input-group-prepend">
	          <span class="input-group-text"><i class="far fa-phone"></i></span>
	        </div>
	        <%= f.telephone_field :phone, class: 'form-control', placeholder: :phone %>
	      </div>
	    </div>
	    <!-- Email -->
	    <div class="form-group col-md-6 mb-2">
	      <div class="input-group input-group-merge input-group-alternative mb-3">
	        <div class="input-group-prepend">
	          <span class="input-group-text"><i class="far fa-envelope"></i></span>
	        </div>
	        <%= f.email_field :email, class: 'form-control', placeholder: :email, required: true %>
	      </div>
	    </div>
    </div>

    <div class="row">
	    <!-- Gender -->
	    <div class="form-group col-md-6 mb-2">
	      <div class="input-group input-group-merge input-group-alternative mb-3">
	        <div class="input-group-prepend">
	          <span class="input-group-text input-group-select2"><i class="far fa-venus-mars"></i></span>
	        </div>
	        <%= f.select :gender, options_for_select({ t('general.gender.male').titleize => 0, t('general.gender.female').titleize => 1, t('general.gender.unspecified').titleize => 2 }, (@staff.user.gender if @staff.user)), {}, { 
	        	class: 'form-control', required: true, data: {
	        		toggle: 'select', 
	        		placeholder: t('activerecord.attributes.user.gender'),
	        		'minimum-results-for-search': "Infinity"
	        	}
	        } %>
	      </div>
	    </div>

	    <!-- Date of birth -->
	    <div class="form-group col-md-6 mb-2">
	      <div class="input-group input-group-merge input-group-alternative mb-3">
	        <div class="input-group-prepend">
	          <span class="input-group-text"><i class="far fa-calendar"></i></span>
	        </div>
	        <%= f.date_field :birth_date, class: 'form-control', placeholder: :birth_date %>
	      </div>
	    </div>
	  </div>
	  
	  <!-- Avatar -->
	  <div class="form-group col-12 px-0">
      <div class="input-group input-group-merge input-group-alternative mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="far fa-photo"></i></span>
        </div>
        <%= f.file_field :avatar, class: 'form-control' %>
      </div>
    </div>
	<% end %>
	<%= form.hidden_field :initial_password, value: staff.initial_password %>
	<div class="card-footer pl-0">
	  <%= form.submit class: 'btn btn-success' %>
	</div>
<% end %>

app/views/staffs/_staff.html.erb
<%= link_to staff, class: 'person-container', data: { :user_id => staff.user.id } do %>
  <div class="media align-items-center <%= 'mb-2' unless local_assigns[:no_margin_bottom] %> star-floating <%= 'px-3 py-2 rounded border shadow-sm' if local_assigns[:boxed] %> <%= 'bg-white' if local_assigns[:bg_white] %>">

    <% if staff.user.avatar.attached? %>
      <div class="avatar avatar-<%= local_assigns[:avatar_size] || 'md' %> rounded-circle mr-3 table-avatar" style="background-image: url('<%= url_for(staff.user.avatar) %>')" ></div>
    <% else %>
      <% if staff.user.female? # Female %>
        <img src="/images/female-blue.jpg" class="avatar avatar-<%= local_assigns[:avatar_size] || 'md' %> rounded-circle mr-3" />
      <% else # Male or otherwise %>
        <img src="/images/male-blue.jpg" class="avatar avatar-<%= local_assigns[:avatar_size] || 'md' %> rounded-circle mr-3" />
      <% end %>
    <% end %>

    <%= "<span class=\"badge badge-md badge-circle badge-floating badge-warning border-white\" data-toggle=\"tooltip\" title=\"#{ t('activerecord.attributes.classroom.form_tutor') }\"><i class=\"far fa-star\"></i></span>".html_safe if local_assigns[:star] %>

    <div class="media-body overflow-ellipsis <%= 'd-flex justify-content-between align-items-center' if local_assigns[:selectable] %>">
      <span class="name mb-0 <%= 'text-sm' unless local_assigns[:text_lg] %>"><%= staff.user.name %></span>
      <%= link_to(icon('far fa-user-slash'), remove_staff_from_classroom_path(staff, @classroom), class: "table-action float-right", data: { toggle: 'tooltip', 'original-title': t('.remove_from_classroom') }) if local_assigns[:removeable] %>
      <%= '<i class="far fa-check checkmark mr-2" style="display: none"></i>'.html_safe if local_assigns[:selectable] %>
    </div>

  </div>
<% end %>

app/views/staffs/edit.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.staff.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.staff.other').titleize, staffs_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.edit' %> <%= t('activerecord.models.staff.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.edit' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.edit' %> <%= t('activerecord.models.staff.one') %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', staff: @staff %>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), staffs_path, class: 'btn btn-light' %>
</div>

<% content_for(:page_title, "#{t('general.edit')} #{t('activerecord.models.staff.one')}") %>

app/views/staffs/index.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.staff.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t('activerecord.models.staff.other').titleize %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card pb-3">
        <!-- Card header -->
        <div class="card-header border-0">
          <div class="row">
            <div class="col-6">
              <h3 class="mb-0"><%= t 'general.list_of' %> <%= t 'activerecord.models.staff.other' %></h3>
            </div>
            <div class="col-6 text-right">
              <%= link_to new_staff_path, class: "btn btn-sm btn-primary btn-round btn-icon", data: { toggle: :tooltip, 'original-title': "#{ t 'general.add'} #{ t 'activerecord.models.staff.one' }" } do %>
                <span class="btn-inner--icon">
                  <i class="fas fa-plus"></i>
                </span>
                <span class="btn-inner--text"><%= t 'general.add' %></span>
              <% end %>
            </div>
          </div>
        </div>
        <!-- Light table -->
        <div class="table-responsive">
          <table class="table align-items-center table-flush" id="datatable-basic">
            <thead class="thead-light">
              <tr>
                <th><%= t ("activerecord.attributes.user.name") %></th>
                <th><%= t ("activerecord.attributes.user.email") %></th>
                <th><%= t ("activerecord.attributes.user.phone") %></th>
                <th><%= t ("activerecord.attributes.user.active") %></th>
                <th scope="col" class="no-sort"></th>
              </tr>
            </thead>
            <tbody>
              <% @staffs.each do |staff| %>
                <tr>
                  <th scope="row">
                    <%= link_to staff do %>
                      <div class="media align-items-center">
                        <% if staff.user.avatar.attached? %>
                          <div class="avatar rounded-circle mr-3 table-avatar" style="background-image: url('<%= url_for(staff.user.avatar) %>')" ></div>
                        <% else %>
                          <% if staff.user.female? # Female %>
                            <img src="/images/female-blue.jpg" class="avatar rounded-circle mr-3" />
                          <% else # Male or otherwise %>
                            <img src="/images/male-blue.jpg" class="avatar rounded-circle mr-3" />
                          <% end %>
                        <% end %>
                        <div class="media-body">
                          <span class="name mb-0 text-sm"><%= staff.user.name %></span>
                        </div>
                      </div>
                    <% end %>
                  </th>
                  <td><%= staff.user.email %></td>
                  <td><%= staff.user.phone %></td>
                  <td><%= staff.user.active ? icon('far fa-check-circle text-success', ' ' + t('general.active')) : icon('far fa-times-circle text-danger', ' ' + t('general.inactive'))%></td>
                  <td class="table-actions">
                    <!-- View -->
                    <%# link_to '<i class="far fa-eye"></i>'.html_safe, staff, class: "table-action", data: { toggle: 'tooltip', 'original-title': t('general.view') } %>
                    <!-- Edit -->
                    <%= link_to '<i class="far fa-user-edit"></i>'.html_safe, edit_staff_path(staff), class: "table-action", data: { toggle: 'tooltip', 'original-title': t('general.edit') } %>
                    <!-- Activate/deactivate -->
                    <% if staff.user.active %>
                      <%= link_to '<i class="far fa-user-lock"></i>'.html_safe, deactivate_staff_path(staff), class: "table-action", data: { toggle: 'tooltip', 'original-title': t('general.deactivate'), confirm: t('general.are_you_sure_deactivate') } %>
                    <% else %>
                      <%= link_to '<i class="far fa-user-unlock"></i>'.html_safe, activate_staff_path(staff), class: "table-action", data: { toggle: 'tooltip', 'original-title': t('general.activate') } %>
                    <% end %>
                    <!-- Delete -->
                    <%= link_to '<i class="far fa-trash"></i>'.html_safe, staff, class: "table-action table-action-delete", data: { toggle: 'tooltip', 'original-title': t('general.delete'), confirm: t('general.are_you_sure_delete'), remote: true }, method: :delete %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- Card footer -->
        <!-- <div class="card-footer py-4">
          <nav aria-label="...">
            <ul class="pagination justify-content-end mb-0">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">
                  <i class="fa fa-angle-left"></i>
                  <span class="sr-only"><%= t 'general.previous' %></span>
                </a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">2
                  <span class="sr-only">(<%= t 'general.current' %>)</span></a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">3</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">
                  <i class="fa fa-angle-right"></i>
                  <span class="sr-only"><%= t 'general.next' %></span>
                </a>
              </li>
            </ul>
          </nav>
        </div> -->
      </div>

    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

<% content_for(:page_title, "#{ t 'general.list_of' } #{t('activerecord.models.staff.other').titleize}") %>

app/views/staffs/new.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.staff.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.staff.other').titleize, staffs_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.new' %> <%= t('activerecord.models.staff.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.add_new' %> <%= t('activerecord.models.staff.one') %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', staff: @staff %>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), staffs_path, class: 'btn btn-light' %>
</div>

<% content_for(:page_title, "#{t('general.add')} #{t('activerecord.models.staff.one')}") %>

app/views/staffs/show.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.staff.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.staff.other').titleize, staffs_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.new' %> <%= t('activerecord.models.staff.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.show' %> Staff</h4>
    </div>
    <div class="card-body">
      <dl class="row">
	          </dl>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), staffs_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>
  <%= link_to icon('far fa-edit', t('general.edit')), edit_staff_path(@staff), class: 'btn btn btn-icon icon-left btn-warning' %>
  <%= link_to icon('far fa-trash', t('general.delete')), @staff, class: "btn btn btn-icon icon-left btn-danger", data: { confirm: t('general.are_you_sure_delete'), remote: true }, method: :delete %>
</div>

<% content_for(:page_title, t('general.show') + " Staff") %>

app/views/staffs/update.js.erb
reloadWithTurbolinks()