config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :announcements do
    resources :comments
  end
  resources :attendances
  resources :marks
  resources :observations
  resources :students
  resources :parents
  resources :families
  resources :staffs
  resources :schools
  resources :classrooms
  resources :subjects
  resources :activities
  resources :likes
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :activities
      resources :classrooms
      resources :schools
      resources :staffs
      resources :students
    end
  end

  get 'gradebook/:classroom_id', to: 'gradebooks#show_classroom', as: 'gradebook_classroom'
  get 'gradebook', to: 'gradebooks#index', as: 'gradebook'

  get 'user_activities/:id', to: 'user_activities#index', as: 'user_activities'

  get 'staffs/:id/activate', to: 'staffs#activate', as: 'activate_staff'
  get 'staffs/:id/deactivate', to: 'staffs#deactivate', as: 'deactivate_staff'

  get 'students/:id/remove_student_from_classroom/:classroom_id', to: 'students#remove_student_from_classroom', as: 'remove_student_from_classroom'
  get 'transfer_student_to_form', to: 'students#transfer_student_to_form', as: 'transfer_student_to_form'
  get 'add_student_to_optional_classroom', to: 'students#add_student_to_optional_classroom', as: 'add_student_to_optional_classroom'

  get 'staffs/:id/remove_staff_from_classroom/:classroom_id', to: 'staffs#remove_staff_from_classroom', as: 'remove_staff_from_classroom'

  get 'profile', to: 'profile#index', as: 'profile'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :sender, class_name: 'Staff', foreign_key: 'sender_id'
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_and_belongs_to_many :users
  alias recipients users

  after_create :set_scheduled_for_if_empty

  def set_scheduled_for_if_empty
    if scheduled_for.nil?
      scheduled_for = DateTime.now
    end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: %i[ show edit update destroy ]

  def index
    @search = Announcement.reverse_chronologically.ransack(params[:q])

    respond_to do |format|
      format.any(:html, :json) { @announcements = set_page_and_extract_portion_from @search.result }
      format.csv { render csv: @search.result }
    end
  end

  def show
    fresh_when etag: @announcement
  end

  def new
    @announcement = Announcement.new
  end

  def edit
  end

  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.save!

    respond_to do |format|
      format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
      format.json { render :show, status: :created }
    end
  end

  def update
    @announcement.update!(announcement_params)
    respond_to do |format|
      if params[:announcement][:deleted] == 'true'
        format.html { redirect_to announcements_path, notice: 'Announcement was successfully deleted.' }
      elsif params[:announcement][:restore] == 'true'
        format.html { redirect_to announcements_path, notice: 'Announcement was successfully restored.' }
      else
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
      end
      format.json { render :show }
    end
  end

  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    def announcement_params
      params.require(:announcement).permit(:title, :text, :category, :sender_id, :scheduled_for, :deleted, user_ids: [])
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.erb
<%# link_to announcement, class: "list-group-item list-group-item-action flex-column align-items-start py-4 px-4" do %>
<div class="list-group-item list-group-item-action flex-column align-items-start py-4 px-4">
  <div class="d-flex w-100 justify-content-between">
    <div>
      <div class="d-flex w-100 align-items-center">

        <% if announcement.sender.user.avatar.attached? %>
          <div class="avatar avatar-xs mr-2" style="background-image: url('<%= url_for(announcement.sender.user.avatar) %>')" ></div>
        <% else %>
          <% if announcement.sender.user.female? # Female %>
            <img src="/images/female-blue.jpg" class="avatar avatar-xs mr-2" />
          <% else # Male or otherwise %>
            <img src="/images/male-blue.jpg" class="avatar avatar-xs mr-2" />
          <% end %>
        <% end %>

        <h5 class="mb-1"><%= announcement.sender.user.name %></h5>
      </div>
    </div>
    <div>
      <% if user_signed_in? && current_user.id == announcement.sender.id %>
        <% if announcement.deleted %>
          <%= link_to announcement_path(announcement, { announcement: { deleted: false, restore: true } }), method: :patch do %>
            <i class="far fa-trash-restore-alt text-info" data-toggle="tooltip" data-placement="left" title="<%= t 'general.restore' %>"></i>
          <% end %>
        <% else %>
          <%= link_to announcement_path(announcement, { announcement: { deleted: true } }), method: :patch do %>
            <i class="far fa-trash-alt text-danger" data-toggle="tooltip" data-placement="left" title="<%= t 'general.delete' %>"></i>
          <% end %>
        <% end %>
      <% end %>
      <small><%= l announcement.scheduled_for %></small>
    </div>
  </div>
  <%= link_to announcement do %>
    <% case announcement.category when 'alert' %>
      <h4 class="mb-1 mt-3 d-inline-block text-danger"><i class="far fa-fw fa-siren-on"></i>&nbsp; <%= announcement.title %></h5>
    <% when 'reminder' %>
      <h4 class="mb-1 mt-3 d-inline-block text-success"><i class="far fa-fw fa-alarm-exclamation"></i>&nbsp; <%= announcement.title %></h5>
    <% else %>
      <h4 class="mb-1 mt-3 d-inline-block"><i class="far fa-fw fa-scroll"></i>&nbsp; <%= announcement.title %></h5>
    <% end %>

    <% if announcement.likes.any? || announcement.comments.any? %>
      <span class="badge badge-secondary">
        <% if announcement.likes.any? %>
          <%= announcement.likes.size %> <i class="far fa-thumbs-up"></i>
        <% end %>
        <% if announcement.comments.any? %>
          &ensp;<%= announcement.comments.size %> <i class="far fa-comment-alt-dots"></i>
        <% end %>
      </span>
    <% end %>
  <% end %>
  <p class="text-sm mb-0 overflow-ellipsis">
    <%= strip_tags(announcement.text).split.join(' ') %>
  </p>
</div>

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, data: { controller: 'validation' }) do |form| %>

  <ul class="list-group">
    <%# From %>
    <li class="list-group-item">
      <i class="far fa-user-tie fa-fw"></i>&ensp;<%= t '.from' %>&ensp;<%= current_user.name %>
    </li>

    <%# To %>
    <li class="list-group-item" id="recipients-section">
      <i class="far fa-users fa-fw"></i><span>&ensp;<%= t '.to' %>&ensp;</span>
      <span id="selected-span"><span id="number-selected"><%= t '.zero' %></span> <%= t '.recipients_selected' %></span>&ensp;
      <a href="javascript:;" id="select-recipients-button" class="btn btn-sm btn-primary"><%= t '.choose_recipients' %></a>
    </li>

    <%# Subject %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-auto mt-1">
          <i class="far fa-pen-nib fa-fw"></i>&ensp;<%= t '.subject' %>&ensp;
        </div>
        <div class="col">
          <%= form.text_field :title, class: 'form-control form-control-sm form-control-flush border-bottom', required: true %>
        </div>
      </div>
    </li>
  </ul>

  <%= form.hidden_field :sender_id, value: current_user.id %>

  <%# Hidden select %>
  <div class="form-group mb-2 d-none">
    <div class="input-group input-group-merge input-group-alternative mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text input-group-select2"><i class="far fa-users"></i></span>
      </div>
      <%= form.select(:user_ids, grouped_options_for_select([
          [t('activerecord.models.staff.other'), Staff.joins(:user).order(:first_name).collect {|v| [ v.name, v.user.id ] } ],
          [t('activerecord.models.student.other'), Student.includes(:user).order('users.first_name').collect {|v| [ v.name, v.user.id ] } ]
        ], (@announcement.user_ids if @announcement) ), {
        include_blank: true
      }, { 
          class: 'form-control',
          id: 'users-select-field',
          multiple: 'true',
          data: { 
            controller: 'select', 
            toggle: 'select', 
            placeholder: t('activerecord.models.subject.one')	        		
          } 
    }) %>
    </div>
  </div>

  <%# Text %>
  <div class="form-group my-4" data-controller="summernote">
      <%= form.text_area :text, class: 'form-control', data: { editor: 'summernote' } %>
  </div>

  <%# Message type %>
  <ul class="list-group">
    <li class="list-group-item">
      <div class="row">
        <div class="col-auto mt-1">
          <i class="far fa-mail-bulk fa-fw"></i>&ensp;<%= t 'activerecord.attributes.announcement.category' %>&ensp;
        </div>
        <div class="col">
          <%= form.select :category, options_for_select({ 
            t('announcements.categories.simple').titleize => 'simple', 
            t('announcements.categories.reminder').titleize => 'reminder', 
            t('announcements.categories.alert').titleize => 'alert',
          }, (@announcement.category || 'simple')), {}, { 
            class: 'form-control form-control-sm', required: true, data: {
              toggle: 'select', 
              placeholder: t('activerecord.attributes.announcement.category'),
              'minimum-results-for-search': "Infinity"
            }
          } %>
        </div>
      </div>
    </li>

    <%# Scheduled for %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-auto mt-1">
          <i class="far fa-calendar fa-fw"></i>&ensp;<%= t 'activerecord.attributes.announcement.scheduled_for' %>&ensp;
        </div>
        <div class="col">
          <%= form.datetime_field :scheduled_for, class: 'form-control form-control-sm form-control-flush border-bottom' %>
        </div>
      </div>
    </li>

  </ul>

<div class="card-footer pl-0">
  <%= form.submit class: 'btn btn-success', id: 'submit-button' %>
</div>
<% end %>

<script>
  window.selected_people = []

  $(document).ready(function () {
    $('#users-select-field').find(':selected').each(function (index, element) {
      window.selected_people.push( parseInt($(element).val()) )
    });

    if (window.selected_people.length == 0) {
      $('#selected-span').text( '<%= t 'announcements.form.no_recipients_selected' %>' )
    } else if (window.selected_people.length == 1) {
      $('#selected-span').text( $('#users-select-field').find('[value="' + window.selected_people[0] + '"]').text() )
    } else {
      $('#selected-span').text( String(window.selected_people.length) + ' <%= t 'announcements.form.recipients_selected' %>' )
    }
  });

  $('#select-recipients-button').click(function (e) { 
    e.preventDefault();
    $("#modal-window").find(".modal-content").html("<%= j (render 'select_recipients_modal') %>");

    $('.person-container').each(function (index, element) {
      if (window.selected_people.includes($(this).data('user-id'))) {
        $(this).find('i.checkmark').show()
      }
    });

    $('#modal-window').modal('show');
    const open_modal = new Event('modal-opened')

    $('#modal-submit').on('click', function() {
      $('#modal-window').modal('hide');
      const event = new Event('modal-closed')
    });
  });

  $('#submit-button').click(function (e) {
    if (window.selected_people.length == 0) {
      e.preventDefault();
      $('#recipients-section').addClass('bg-gradient-danger');
      $('#recipients-section').contents().css('color', 'white')
      $('<div class="text-white small d-inline"><i class="far fa-exclamation-triangle"></i> <%= t '.error_minimum_recipients' %></div>').insertAfter('#select-recipients-button');
      $('html, body').stop().animate({ scrollTop: $('#recipients-section').offset().top }, 500);
    }    
  });

</script>

app/views/announcements/edit.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.announcement.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.announcement.other').titleize, announcements_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.edit' %> <%= t('activerecord.models.announcement.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.edit' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.edit' %> <%= t('activerecord.models.announcement.one') %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', announcement: @announcement %>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), announcements_path, class: 'btn btn-light' %>
</div>

<% content_for(:page_title, "#{t('general.edit')} #{t('activerecord.models.announcement.one')}") %>

app/views/announcements/index.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.announcement.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t('activerecord.models.announcement.other').titleize %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-lg-3 col-md-6 col-12">
      <div class="card">
        <div class="card-header">
          <%= link_to icon('far fa-pen-nib', t('announcements.compose')), new_announcement_path, class: 'btn btn-success btn-block' %>
        </div>
        <div class="card-body p-0">

          <div class="list-group list-group-flush" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <!-- Received -->
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">
              <div><i class="far fa-fw fa-inbox"></i>&nbsp; <%= t('.inbox') %></div>
              <% if Announcement.joins(:users).where('users.id = ?  AND scheduled_for <= ?  AND deleted = false', current_user.id.to_s, DateTime.now.to_s).any? %>
                <span class="badge badge-primary badge-pill"><%= Announcement.joins(:users).where('users.id = ?  AND scheduled_for <= ?  AND deleted = false', current_user.id.to_s, DateTime.now.to_s).size %></span>
              <% end %>
            </a>
            <!-- Sent -->
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">
              <div><i class="far fa-fw fa-paper-plane"></i>&nbsp; <%= t('.sent') %></div>
              <% if Announcement.where('sender_id = ? AND scheduled_for <= ?  AND deleted = false', current_user.id, DateTime.now.to_s).any? %>
                <span class="badge badge-primary badge-pill"><%= Announcement.where('sender_id = ? AND scheduled_for <= ?  AND deleted = false', current_user.id, DateTime.now.to_s).size %></span>
              <% end %>
            </a>
            <!-- Scheduled -->
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">
              <div><i class="far fa-fw fa-clock"></i>&nbsp; <%= t('.scheduled') %></div>
              <% if Announcement.where('sender_id = ? AND scheduled_for > ?  AND deleted = false', current_user.id, DateTime.now.to_s).any? %>
                <span class="badge badge-primary badge-pill"><%= Announcement.where('sender_id = ? AND scheduled_for > ?  AND deleted = false', current_user.id, DateTime.now.to_s).size %></span>
              <% end %>
            </a>
            <!-- Deleted -->
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center rounded-bottom" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">
              <div><i class="far fa-fw fa-trash-alt"></i>&nbsp; <%= t('.deleted') %></div>
              <% if Announcement.where('sender_id = ? AND deleted = true', current_user.id).any? %>
                <span class="badge badge-primary badge-pill"><%= Announcement.where('sender_id = ? AND deleted = true', current_user.id).size %></span>
              <% end %>
            </a>
          </div>

        </div>
      </div>
    </div>
    
    <div class="col-lg-9 col-md-6 col-12">
      <div class="card pb-3">
        <!-- Card header -->
        <div class="card-header border-0">
          <div class="row">
            <div class="col-12">
              <h3 class="mb-0"><%= t 'general.list_of' %> <%= t 'activerecord.models.announcement.other' %></h3>
            </div>
            <!-- <div class="col-6 text-right">
              <%= link_to new_announcement_path, class: "btn btn-sm btn-primary btn-round btn-icon", data: { toggle: :tooltip, 'original-title': "#{ t 'general.add'} #{ t 'activerecord.models.announcement.one' }" } do %>
                <span class="btn-inner--icon">
                  <i class="fas fa-plus"></i>
                </span>
                <span class="btn-inner--text"><%= t 'general.add' %></span>
              <% end %>
            </div> -->
          </div>
        </div>
        <!-- Card body -->
        <div class="card-body p-0">
          <div class="tab-content" id="v-pills-tabContent">

            <%# Received tab %>
            <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
              <div class="list-group list-group-flush">
                <%= render Announcement.joins(:users).where('users.id = ? AND scheduled_for <= ? AND deleted = false', current_user.id.to_s, DateTime.now.to_s).order(:scheduled_for => :desc) %>
              </div>
            </div>


            <%# Sent tab %>
            <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
              <div class="list-group list-group-flush">
                <%= render Announcement.where('sender_id = ? AND scheduled_for <= ?  AND deleted = false', current_user.id, DateTime.now.to_s).order(:scheduled_for => :desc) %>
              </div>
            </div>


            <%# Scheduled %>
            <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
              <div class="list-group list-group-flush">
                <%= render Announcement.where('sender_id = ? AND scheduled_for > ?  AND deleted = false', current_user.id, DateTime.now.to_s).order(:scheduled_for => :desc) %>
              </div>
            </div>


            <%# Deleted %>
            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
              <div class="list-group list-group-flush">
                <%= render Announcement.where('sender_id = ? AND deleted = true', current_user.id).order(:scheduled_for => :desc) %>
              </div>
            </div>
          </div>

          
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

<% content_for(:page_title, "#{ t 'general.list_of' } #{t('activerecord.models.announcement.other').titleize}") %>

app/views/announcements/show.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.announcement.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.announcement.other').titleize, announcements_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.new' %> <%= t('activerecord.models.announcement.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <% case @announcement.category when 'alert' %>
        <h3 class="mb-0 text-danger"><i class="far fa-fw fa-siren-on"></i>&nbsp; <%= @announcement.title %></h3>
      <% when 'reminder' %>
        <h3 class="mb-0 text-success"><i class="far fa-fw fa-alarm-exclamation"></i>&nbsp; <%= @announcement.title %></h3>
      <% else %>
        <h3 class="mb-0"><i class="far fa-fw fa-scroll"></i>&nbsp; <%= @announcement.title %></h3>
      <% end %>
    </div>
    <div class="card-body p-0 pb-1">
      <ul class="list-group list-group-flush">
        <%# Sender %>
        <li class="list-group-item">
          <div class="row">
            <div class="col">
              <%= render @announcement.sender, no_margin_bottom: true, text_lg: true, avatar_size: 'sm' %>
            </div>
            <div class="col-auto">
              <p class="mb-0 mt-1"><%= l @announcement.scheduled_for %></p>
            </div>
          </div>
        </li>

        <%# Recipients %>
        <li class="list-group-item">
          <% if @announcement.recipients.size > 1 %>
            <%= t '.to' %> <%= @announcement.recipients.size %> <%= t('.recipients') %>&ensp;
            <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
              <i class="far fa-users"></i>&nbsp; <%= t '.view_recipients' %>
            </a>

            <div class="collapse" id="collapseExample">
              <div class="mt-3">
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                  <% @announcement.recipients.each do |recipient| %>
                    <div class="col">
                      <% if recipient.profile_type == 'Student' %>
                        <%= render 'students/student_avatar_name', student: recipient.profile, boxed: true %>
                      <% else %>
                        <%= render recipient.profile, boxed: true %>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="row">
              <div class="col-auto pr-0">
                <%= t '.to' %>
              </div>
              <div class="col">
                <% if @announcement.recipients.first.profile_type == 'Student' %> 
                  <%= render('students/student_avatar_name', student: @announcement.recipients.first.profile, avatar_size: 'xs', no_margin_bottom: true) %>
                <% else %> 
                  <%= render(@announcement.recipients.first.profile, avatar_size: 'xs', no_margin_bottom: true) %>
                <% end %>
              </div>
            </div>
          <% end %>
        </li>

        <%# Message %>
        <li class="list-group-item pb-0">
          <%= @announcement.text.html_safe %>
        </li>

        <%# Likes %>
        <li class="list-group-item">
          <% if Like.where(user_id: current_user.id, likeable: @announcement).any? %>

            <%= link_to like_path(Like.where(user_id: current_user.id, likeable: @announcement).first, likeable_gid: @announcement.to_global_id), method: :delete, remote: true, class: 'btn btn-primary btn-sm', id: 'unlike-button' do %>
              <%= icon('far fa-thumbs-down', 'Unlike') %>
              <span class="badge badge-neutral"><%= @announcement.likes.count %></span>
            <% end %>

          <% else %>

            <%= link_to likes_path(likeable_gid: @announcement.to_global_id), method: :post, remote: true, class: 'btn btn-primary btn-sm', id: 'like-button' do %>
              <%= icon('far fa-thumbs-up', 'Like') %>
              <span class="badge badge-neutral" ><%= @announcement.likes.count %></span>
            <% end %>

          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <p class="font-weight-bold">
        <i class="far fa-comments-alt"></i> 
        <%= t 'activerecord.models.comment.other' %>&ensp;
        <span class="badge badge-default"><%= @announcement.comments.size %></span>
      </p>
      <%= form_with(model: [@announcement, @announcement.comments.build]) do |f| %>
        <div class="form-group mb-0">
          <div class="input-group">
            <%= f.text_area :body, class: 'form-control' %>
            <div class="input-group-append">
              <%= f.button :submit, class: 'btn btn-default' do %>
                <i class="far fa-comment-alt-plus"></i>
              <% end %>
            </div>
          </div>
          
        </div>
        
      <% end %>
    </div>
  </div>

  <%= render @announcement.comments.order(created_at: :desc) %>

  <%= link_to icon('far fa-arrow-left', t('general.back')), announcements_path, class: 'btn btn-sm btn-icon icon-left btn-secondary d-mobile-none' %>
  <%= link_to icon('far fa-edit', t('general.edit')), edit_announcement_path(@announcement), class: 'btn btn-sm btn-icon icon-left btn-warning' %>
  <%= link_to icon('far fa-trash', t('general.delete')), @announcement, class: "btn btn-sm btn-icon icon-left btn-danger", data: { confirm: t('general.are_you_sure_delete'), remote: true }, method: :delete %>
</div>

<% content_for(:page_title, t('general.show') + " Announcement") %>