config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :announcements do
    resources :comments
  end
  resources :attendances
  resources :marks
  resources :observations
  resources :students
  resources :parents
  resources :families
  resources :staffs
  resources :schools
  resources :classrooms
  resources :subjects
  resources :activities
  resources :likes
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :activities
      resources :classrooms
      resources :schools
      resources :staffs
      resources :students
    end
  end

  get 'gradebook/:classroom_id', to: 'gradebooks#show_classroom', as: 'gradebook_classroom'
  get 'gradebook', to: 'gradebooks#index', as: 'gradebook'

  get 'user_activities/:id', to: 'user_activities#index', as: 'user_activities'

  get 'staffs/:id/activate', to: 'staffs#activate', as: 'activate_staff'
  get 'staffs/:id/deactivate', to: 'staffs#deactivate', as: 'deactivate_staff'

  get 'students/:id/remove_student_from_classroom/:classroom_id', to: 'students#remove_student_from_classroom', as: 'remove_student_from_classroom'
  get 'transfer_student_to_form', to: 'students#transfer_student_to_form', as: 'transfer_student_to_form'
  get 'add_student_to_optional_classroom', to: 'students#add_student_to_optional_classroom', as: 'add_student_to_optional_classroom'

  get 'staffs/:id/remove_staff_from_classroom/:classroom_id', to: 'staffs#remove_staff_from_classroom', as: 'remove_staff_from_classroom'

  get 'profile', to: 'profile#index', as: 'profile'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_alert_validation.html.erb
<!-- USE THIS PARTIAL INSIDE FORM IF YOU WANT TO USE SERVER SIDE VALIDATION -->
<% if resource.errors.present? %>
  <div class="alert alert-danger alert-dismissible show fade">
    <div class="alert-body">
      <button class="close" data-dismiss="alert"><span>&times;</span></button>
      <h5>Please correct the following items and try again:</h5>
      <ul class="pl-3">
        <% resource.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_authentication_header.html.erb
<div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
  <div class="container">
    <div class="header-body text-center mb-7">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-8 px-5">
          <h1 class="text-white"><%= title %></h1>
          <p class="text-lead text-white"><%= subtitle %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="separator separator-bottom separator-skew zindex-100">
    <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
    </svg>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer pt-0">
  <div class="row align-items-center justify-content-lg-between">
    <div class="col-lg-6">
      <div class="copyright text-center  text-lg-left  text-muted">
        © 2020
        <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
      </div>
    </div>
    <div class="col-lg-6">
      <ul class="nav nav-footer justify-content-center justify-content-lg-end">
        <li class="nav-item">
          <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
        </li>
        <li class="nav-item">
          <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
        </li>
        <li class="nav-item">
          <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
        </li>
        <li class="nav-item">
          <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<head>
  <title>Argon Starter App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="<%= yield(:meta_description) %>">
  <!--meta name="turbolinks-cache-control" content="no-preview"-->
  <meta name="turbolinks-cache-control" content="no-cache">

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <script>
    var reloadWithTurbolinks = (function () {
      var scrollPosition

      function reload () {
        scrollPosition = [window.scrollX, window.scrollY]
        Turbolinks.visit(window.location.toString(), { action: 'replace' })
      }

      document.addEventListener('turbolinks:load', function () {
        if (scrollPosition) {
          window.scrollTo.apply(window, scrollPosition)
          scrollPosition = null
        }
      })

      return reload
    })()
  </script>

  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&family=Inter&family=Space+Mono&display=swap" rel="stylesheet">
</head>

app/views/shared/_header.html.erb
<div class="row align-items-center py-4">
  <div class="col-lg-6 col-7">
    <h6 class="h2 text-white d-inline-block mb-0"><%= breadcrumb_2 %></h6>
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
      <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="#"><i class="<%= icon %>"></i></a></li>
        <li class="breadcrumb-item"><a href="#"><%= breadcrumb_1 %></a></li>
        <li class="breadcrumb-item active" aria-current="page"><%= breadcrumb_2 %></li>
      </ol>
    </nav>
  </div>
  <div class="col-lg-6 col-5 text-right">
    <a href="#" class="btn btn-sm btn-neutral">New</a>
    <a href="#" class="btn btn-sm btn-neutral">Filters</a>
  </div>
</div>

app/views/shared/_logged_out_footer.html.erb
<footer class="py-5" id="footer-main">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
          &copy; 2020 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
        </div>
      </div>
      <div class="col-xl-6">
        <ul class="nav nav-footer justify-content-center justify-content-xl-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_profile_header.html.erb
<div id="profile-header" class="header pb-6 d-flex align-items-center">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white">Hello Jesse</h1>
        <p class="text-white mt-0 mb-5">This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks</p>
        <a href="#!" class="btn btn-neutral">Edit profile</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_profile_summary_card.html.erb
<div class="card card-profile">
  <%= image_tag "theme/img-1-1000x600.jpg", class: "card-img-top", alt: "Image placeholder" %>
  <div class="row justify-content-center">
    <div class="col-lg-3 order-lg-2">
      <div class="card-profile-image">
        <a href="#">
          <%= image_tag 'theme/team-4.jpg', class: 'rounded-circle' %>
        </a>
      </div>
    </div>
  </div>
  <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
    <div class="d-flex justify-content-between">
      <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
      <a href="#" class="btn btn-sm btn-default float-right">Message</a>
    </div>
  </div>
  <div class="card-body pt-0">
    <div class="row">
      <div class="col">
        <div class="card-profile-stats d-flex justify-content-center">
          <div>
            <span class="heading">22</span>
            <span class="description">Friends</span>
          </div>
          <div>
            <span class="heading">10</span>
            <span class="description">Photos</span>
          </div>
          <div>
            <span class="heading">89</span>
            <span class="description">Comments</span>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center">
      <h5 class="h3">
        Jessica Jones<span class="font-weight-light">, 27</span>
      </h5>
      <div class="h5 font-weight-300">
        <i class="ni location_pin mr-2"></i>Bucharest, Romania
      </div>
      <div class="h5 mt-4">
        <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
      </div>
      <div>
        <i class="ni education_hat mr-2"></i>University of Computer Science
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidenav.html.erb
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scroll-wrapper scrollbar-inner" style="position: relative;"><div class="scrollbar-inner scroll-content" style="height: 1005.5px; margin-bottom: 0px; margin-right: 0px; max-height: none;">
      <!-- Brand -->
      <div class="sidenav-header d-flex align-items-center">
        <a class="navbar-brand" href="../../pages/dashboards/dashboard.html">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "brand/blue.png", class: "navbar-brand-img", alt: "logo" %>
        <% end %>
        <div class="ml-auto">
          <!-- Sidenav toggler -->
          <div class="sidenav-toggler d-none d-xl-block active" data-action="sidenav-unpin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="<%= active_nav_item('home', 'index') %>">
              <%= link_to root_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-columns text-primary"></i>
                <span class="ml-2 nav-link-text"><%= t 'pages.dashboard.title' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('staffs', 'index') %>">
              <%= link_to staffs_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-user-tie text-warning"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.staff.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('families', 'index') %>">
              <%= link_to families_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-users text-info"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.family.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('students', 'index') %>">
              <%= link_to students_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-user-graduate text-success"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.student.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('classrooms', 'index') %>">
              <%= link_to classrooms_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-users-class text-danger"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.classroom.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('schools', 'index') %>">
              <%= link_to schools_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-school text-warning"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.school.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('subjects', 'index') %>">
              <%= link_to subjects_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-chalkboard text-indigo"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.subject.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('activities', 'index') %>">
              <%= link_to activities_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-calendar-alt text-cyan"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.activity.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('user_activities', 'index') %>">
              <%= link_to user_activities_path(current_user.id), class: "nav-link px-3" do %>
                <i class="far fa-fw fa-calendar-star text-yellow"></i>
                <span class="ml-2 nav-link-text"><%= t 'user_activities.index.title' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('announcements', 'index') %>">
              <%= link_to announcements_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-bullhorn text-danger"></i>
                <span class="ml-2 nav-link-text"><%= t 'activerecord.models.announcement.other' %></span>
              <% end %>
            </li>
            <li class="<%= active_nav_item('gradebooks', 'index') %>">
              <%= link_to gradebook_path, class: "nav-link px-3" do %>
                <i class="far fa-fw fa-address-book text-primary"></i>
                <span class="ml-2 nav-link-text"><%= t 'gradebooks.index.title' %></span>
              <% end %>
            </li>
          </ul>
          <!-- Divider -->
          <hr class="my-3">
          <!-- Heading -->
          <h6 class="navbar-heading p-0 text-muted">Documentation</h6>
          <!-- Navigation -->
          <ul class="navbar-nav mb-md-3">
            <li class="nav-item">
              <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html" target="_blank">
                <i class="ni ni-spaceship"></i>
                <span class="nav-link-text">Getting started</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html" target="_blank">
                <i class="ni ni-palette"></i>
                <span class="nav-link-text">Foundation</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html" target="_blank">
                <i class="ni ni-ui-04"></i>
                <span class="nav-link-text">Components</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/plugins/charts.html" target="_blank">
                <i class="ni ni-chart-pie-35"></i>
                <span class="nav-link-text">Plugins</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div><div class="scroll-element scroll-x"><div class="scroll-element_outer"><div class="scroll-element_size"></div><div class="scroll-element_track"></div><div class="scroll-bar" style="width: 0px; left: 0px;"></div></div></div><div class="scroll-element scroll-y"><div class="scroll-element_outer"><div class="scroll-element_size"></div><div class="scroll-element_track"></div><div class="scroll-bar" style="height: 0px;"></div></div></div></div>
  </nav>

app/views/shared/_toastr.html.erb
<% flash.each do |type, msg| %>
  <% if msg.present? && msg.is_a?(String) %>
    <div data-controller="toastr" data-toastr-type="<%= type %>" data-toastr-message="<%= msg %>"></div>
  <% end %>
<% end %>

app/views/shared/_topnav.html.erb
<%
unless defined?(bg_color_class)
  bg_color_class = 'bg-primary'
end
%>

<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom <%= bg_color_class %>">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><%= icon 'far fa-search' %></span>
            </div>
            <input class="form-control" placeholder="Search" type="text">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.</h6>
            </div>
            <!-- List group -->
            <div class="list-group list-group-flush">
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                      <%= image_tag "theme/team-1.jpg", alt: "Image placeholder", class: "avatar rounded-circle" %>
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                      <%= image_tag "theme/team-2.jpg", alt: "Image placeholder", class: "avatar rounded-circle" %>
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                      <%= image_tag "theme/team-3.jpg", alt: "Image placeholder", class: "avatar rounded-circle" %>
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>5 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Your posts have been liked a lot.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                      <%= image_tag "theme/team-4.jpg", alt: "Image placeholder", class: "avatar rounded-circle" %>
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                      <%= image_tag "theme/team-5.jpg", alt: "Image placeholder", class: "avatar rounded-circle" %>
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
            </div>
            <!-- View all -->
            <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>Calendar</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
                <small>Email</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-pin-3"></i>
                </span>
                <small>Maps</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                  <i class="ni ni-basket"></i>
                </span>
                <small>Shop</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center ml-auto ml-md-0 ">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <% if current_user.avatar.attached? %>
                  <div class="avatar avatar-sm rounded-circle mr-2" style="background-image: url('<%= url_for(current_user.avatar) %>')" ></div>
                <% else %>
                  <% if current_user.female? # Female %>
                    <img src="/images/female-blue.jpg" class="avatar avatar-sm rounded-circle mr-2" />
                  <% else # Male or otherwise %>
                    <img src="/images/male-blue.jpg" class="avatar avatar-sm rounded-circle mr-2" />
                  <% end %>
                <% end %>
                <% case current_user.profile_type when 'Staff' %>
                  <span class="badge badge-md badge-circle badge-floating badge-indigo shadow-lg topnav-profile-badge d-none d-sm-flex"><i class="far fa-user-tie"></i></span>
                <% when 'Student' %>
                  <span class="badge badge-md badge-circle badge-floating badge-yellow shadow-lg topnav-profile-badge d-none d-sm-flex"><i class="far fa-user-graduate"></i></span>
                <% when 'Parent' %>
                  <span class="badge badge-md badge-circle badge-floating badge-success shadow-lg topnav-profile-badge d-none d-sm-flex"><i class="far fa-user-friends"></i></span>
                <% else %>
                  <span class="badge badge-md badge-circle badge-floating badge-info shadow-lg topnav-profile-badge d-none d-sm-flex"><i class="far fa-user"></i></span>
                <% end %>

                <div class="media-body ml-2 d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold"><%= current_user.name %></span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu  dropdown-menu-right ">
              <div class="dropdown-header noti-title">
                <h6 class="text-overflow m-0"><%= t '.welcome' %></h6>
              </div>

              <% if current_user.is_staff? %>
                <%= link_to current_user.profile.current_school, class: 'dropdown-item' do %>
                  <i class="far fa-fw fa-school"></i>
                  <span><%= current_user.profile.current_school.name %></span>
                <% end %>

                <% (current_user.profile.schools - [current_user.profile.current_school]).each do |school| %>

                  <%= form_with(model: current_user.profile, data: { controller: 'validation' }, remote: true, local: false) do |form| %>
                    <%= form.hidden_field :current_school_id, value: school.id %>
                    <%= form.button :submit, class: 'dropdown-item' do %>
                      <i class="far fa-fw fa-exchange"></i>
                      <span><%= school.name %></span>
                    <% end %>
                  <% end %>

                <% end %>
                <div class="dropdown-divider"></div>
              <% end %>

              <%= link_to profile_path, class: 'dropdown-item' do %>
                <i class="far fa-fw fa-user"></i>
                <span><%= t '.profile' %></span>
              <% end %>
              <a href="#!" class="dropdown-item">
                <i class="far fa-fw fa-cog"></i>
                <span><%= t '.settings' %></span>
              </a>
              <a href="#!" class="dropdown-item">
                <i class="far fa-fw fa-calendar-day"></i>
                <span><%= t '.activity' %></span>
              </a>
              <a href="#!" class="dropdown-item">
                <i class="far fa-fw fa-life-ring"></i>
                <span><%= t '.support' %></span>
              </a>
              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_path, class: "dropdown-item", method: :delete do %>
                <i class="far fa-fw fa-sign-out"></i>
                <span><%= t '.logout' %></span>
              <% end %>
            </div>
          </li>
        <% else %>
          <%= link_to icon("far fa-sign-out", ' ' + t('home.index.login')), new_user_session_path, class: 'btn btn-default btn-icon ml-2' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>