config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :announcements do
    resources :comments
  end
  resources :attendances
  resources :marks
  resources :observations
  resources :students
  resources :parents
  resources :families
  resources :staffs
  resources :schools
  resources :classrooms
  resources :subjects
  resources :activities
  resources :likes
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :activities
      resources :classrooms
      resources :schools
      resources :staffs
      resources :students
    end
  end

  get 'gradebook/:classroom_id', to: 'gradebooks#show_classroom', as: 'gradebook_classroom'
  get 'gradebook', to: 'gradebooks#index', as: 'gradebook'

  get 'user_activities/:id', to: 'user_activities#index', as: 'user_activities'

  get 'staffs/:id/activate', to: 'staffs#activate', as: 'activate_staff'
  get 'staffs/:id/deactivate', to: 'staffs#deactivate', as: 'deactivate_staff'

  get 'students/:id/remove_student_from_classroom/:classroom_id', to: 'students#remove_student_from_classroom', as: 'remove_student_from_classroom'
  get 'transfer_student_to_form', to: 'students#transfer_student_to_form', as: 'transfer_student_to_form'
  get 'add_student_to_optional_classroom', to: 'students#add_student_to_optional_classroom', as: 'add_student_to_optional_classroom'

  get 'staffs/:id/remove_staff_from_classroom/:classroom_id', to: 'staffs#remove_staff_from_classroom', as: 'remove_staff_from_classroom'

  get 'profile', to: 'profile#index', as: 'profile'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :subject, optional: true
  belongs_to :coordinator, class_name: "Staff", foreign_key: "coordinator_id", optional: true
  belongs_to :activityable, polymorphic: true, optional: true

  has_many :attendances, dependent: :destroy
	has_many :marks, dependent: :destroy

  has_many :students, through: :attendances

  scope :one_time, -> { where(:start_recur => nil) }
  scope :recurring, -> { where.not(:start_recur => nil) }

  def activityable_gid
    activityable&.to_global_id
  end
  
  def activityable_gid=(gid)
    self.activityable = GlobalID::Locator.locate gid
  end  

  def for_classroom?
    activityable_type == 'Classroom'
  end

  def for_student?
    activityable_type == 'Student'
  end

  def for_school?
    activityable_type == 'School'
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  def index
    if params[:activityable_gid]
      activityable = GlobalID::Locator.locate(params[:activityable_gid])
      @activities = case activityable.class.to_s
      when 'Student'
        puts 'Student!'
        Activity.where(activityable: activityable) + Activity.where(activityable: activityable.form) + Activity.where(activityable: activityable.form.school)
      when 'Classroom'
        puts 'Classroom!'
        Activity.where(activityable: activityable) + Activity.where(activityable: activityable.school)
      else
        puts 'Otherwise!'
        Activity.where(activityable: activityable)
      end

    elsif params[:qdate] && params[:qweekday] && params[:qsubject] && params[:qstudent]
      student = Student.find(params[:qstudent])

      unique_activity = Activity.one_time.where(subject_id: params[:qsubject]).select {|a| a.start.to_date.iso8601 == params[:qdate] && student.has_activity_own_or_inherited?(a) }

      recurring_activity = Activity.recurring.where(subject_id: params[:qsubject]).select {|a| a.start_recur.iso8601 < params[:qdate] && (a.end_recur ? a.end_recur.iso8601 > params[:qdate] : true) && a.days_of_week.include?(params[:qweekday]) && student.has_activity_own_or_inherited?(a) }

      @activities = unique_activity + recurring_activity

      # if @activities.empty?
      #   @activities = Activity.where(subject_id: params[:qsubject])
      # end
        
    else
      @activities = Activity.where(activityable: School.first)
    end

    respond_to do |format|
      format.any(:html, :json) { @activities }
      format.csv { render csv: @activities }
      format.js
    end
  end

  def show
    fresh_when etag: @activity
  end

  def new
    @activity = Activity.new
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.save!

    respond_to do |format|
      format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
      format.json { render :show, status: :created }
      format.js
    end
  end

  def update
    @activity.update!(activity_params)
    respond_to do |format|
      format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
      format.json { render :show }
      format.js
    end
  end

  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:all_day, :start, :end, :start_time, :end_time, :start_recur, :end_recur, :title, :description, :description_staff_only, :creator_id, :coordinator_id, :subject_id, :activityable_gid, days_of_week: [])
    end

    def ajax_params
      {
        all_day: params[:activity][:all_day]
      }
    end
end

app/controllers/api/v1/activities_controller.rb
class Api::V1::ActivitiesController < Api::V1::BaseController
  def index
    if params[:activityable_gid]
      activityable = GlobalID::Locator.locate(params[:activityable_gid])
      @activities = case activityable.class.to_s
      when 'Student'
        Activity.where(activityable: activityable) + Activity.where(activityable: activityable.form) + Activity.where(activityable: activityable.form.school)
      when 'Classroom'
        Activity.where(activityable: activityable) + Activity.where(activityable: activityable.school)
      else
        Activity.where(activityable: activityable)
      end

    elsif params[:qdate] && params[:qweekday] && params[:qsubject] && params[:qstudent]
      student = Student.find(params[:qstudent])

      unique_activity = Activity.one_time.where(subject_id: params[:qsubject]).select {|a| a.start.to_date.iso8601 == params[:qdate] && student.has_activity_own_or_inherited?(a) }

      recurring_activity = Activity.recurring.where(subject_id: params[:qsubject]).select {|a| a.start_recur.iso8601 < params[:qdate] && (a.end_recur ? a.end_recur.iso8601 > params[:qdate] : true) && a.days_of_week.include?(params[:qweekday]) && student.has_activity_own_or_inherited?(a) }

      @activities = unique_activity + recurring_activity
        
    else
      @activities = nil
    end

    render :index, formats: :json
  end

  def show
    @activity = Activity.find(params[:id])

    render :show, formats: :json
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, data: { controller: 'validation' }) do |form| %>
  <div class="form-group">
        <div class="custom-control custom-checkbox">
      <%= form.check_box :all_day, class: 'custom-control-input' %>
      <%= form.label :all_day, class: 'custom-control-label' %>
    </div>
    </div>
  <div class="form-group">
      <%= form.label :start, class: 'form-control-label' %>
        <%= form.datetime_local_field :start, value: l(activity.start), class: 'form-control', data: { controller: 'datetime' } %>
    </div>
  <div class="form-group">
      <%= form.label :end, class: 'form-control-label' %>
        <%= form.datetime_local_field :end, value: l(activity.end), class: 'form-control', data: { controller: 'datetime' } %>
    </div>
  <div class="form-group">
      <%= form.label :days_of_week, class: 'form-control-label' %>
        <%= form.text_field :days_of_week, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :start_time, class: 'form-control-label' %>
        <%= form.text_field :start_time, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :end_time, class: 'form-control-label' %>
        <%= form.text_field :end_time, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :start_recur, class: 'form-control-label' %>
        <%= form.date_field :start_recur, value: l(activity.start_recur), class: 'form-control', data: { controller: 'date' } %>
    </div>
  <div class="form-group">
      <%= form.label :end_recur, class: 'form-control-label' %>
        <%= form.date_field :end_recur, value: l(activity.end_recur), class: 'form-control', data: { controller: 'date' } %>
    </div>
  <div class="form-group">
      <%= form.label :title, class: 'form-control-label' %>
        <%= form.text_field :title, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :description, class: 'form-control-label' %>
        <%= form.text_field :description, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :description_staff_only, class: 'form-control-label' %>
        <%= form.text_field :description_staff_only, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :creator_id, class: 'form-control-label' %>
        <%= form.number_field :creator_id, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :coordinator_id, class: 'form-control-label' %>
        <%= form.number_field :coordinator_id, class: 'form-control' %>
    </div>
  <div class="form-group">
      <%= form.label :subject_id, class: 'form-control-label' %>
        <%= form.collection_select(:subject_id, Subject.all, :id, :to_s, {}, { class: 'form-control', data: { controller: 'select' } }) %>
    </div>
<div class="card-footer pl-0">
  <%= form.submit class: 'btn btn-success' %>
</div>
<% end %>

app/views/activities/create.js.erb
calendar.render()
calendar.getEventSources().forEach(eventSource => eventSource.refetch())
$('#modal-window').modal('hide')

app/views/activities/destroy.js.erb
calendar.render()
calendar.getEventSources().forEach(eventSource => eventSource.refetch())
$('#modal-window').modal('hide')

app/views/activities/edit.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.activity.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.activity.other').titleize, activities_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.edit' %> <%= t('activerecord.models.activity.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.edit' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.edit' %> <%= t('activerecord.models.activity.one') %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', activity: @activity %>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), activities_path, class: 'btn btn-light' %>
</div>

<% content_for(:page_title, "#{t('general.edit')} #{t('activerecord.models.activity.one')}") %>

app/views/activities/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");

$('#modal-window').modal('show');

$('#modal-submit').on('click', function() {
  $('#modal-window').modal('hide');
  const event = new Event('modal-closed')
});

app/views/activities/index.html.erb
<%= javascript_pack_tag 'fullcalendar', 'data-turbolinks-track': 'reload' %>

<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.activity.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t('activerecord.models.activity.other').titleize %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="javascript:;" class="fullcalendar-btn-prev btn btn-sm btn-neutral" onclick="calendar.prev()">
            <i class="far fa-angle-left"></i>
          </a>
          <a href="javascript:;" class="fullcalendar-btn-next btn btn-sm btn-neutral" onclick="calendar.next()">
            <i class="far fa-angle-right"></i>
          </a>
          
          <a href="javascript:;" class="btn btn-sm btn-neutral fc-view-button" onclick="calendar.changeView('dayGridMonth');"><i class="far fa-calendar-alt"></i>&nbsp;<%= t 'calendar.month' %></a>
          <a href="javascript:;" class="btn btn-sm btn-neutral fc-view-button" onclick="calendar.changeView('timeGridWeek');"><i class="far fa-calendar-week"></i>&nbsp;<%= t 'calendar.week' %></a>
          <a href="javascript:;" class="btn btn-sm btn-neutral fc-view-button" onclick="calendar.changeView('timeGridDay');"><i class="far fa-calendar-day"></i>&nbsp;<%= t 'calendar.day' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="row">

    <div class="col-lg-3 col-md-4 col-12">
      <div class="card sticky-top" style="top: 30px">
        <!-- <div class="card-header">
          Select activityable
        </div> -->
        <div class="card-body">
          <div class="dropdown w-100">
            <a class="btn <%= params[:activityable_gid] && GlobalID::Locator.locate(params[:activityable_gid]).class.to_s == 'Classroom' ? 'btn-' + GlobalID::Locator.locate(params[:activityable_gid]).color : 'btn-primary' %> dropdown-toggle btn-block" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= params[:activityable_gid] ? GlobalID::Locator.locate(params[:activityable_gid]).name : 'Choose' %>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <h6 class="dropdown-header"><%= t 'activerecord.models.school.other' %></h6>
              <% School.all.each do |school| %>
                <%= link_to school.name, activities_path(activityable_gid: school.to_global_id), class: 'dropdown-item', remote: true %>
              <% end %>
              <h6 class="dropdown-header"><%= t 'activerecord.models.classroom.other' %></h6>
                <% Classroom.all.each do |classroom| %>
                  <%= link_to classroom.name, activities_path(activityable_gid: classroom.to_global_id), class: 'dropdown-item', remote: true %>
                <% end %>
              <h6 class="dropdown-header"><%= t 'activerecord.models.student.other' %></h6>
                <% Student.all.each do |student| %>
                  <%= link_to student.name, activities_path(activityable_gid: student.to_global_id), class: 'dropdown-item', remote: true %>
                <% end %>
            </div>
          </div>

          <% if Subject.all.any? %>
            <div id="subject-list" class="mt-4">
              <% Subject.all.each do |subject| %>
                <a href="javascript:;" class="subject-draggable btn btn-sm btn-block btn-<%= subject.color %> cursor-grab" data-event='{ 
                  "title": "<%= subject.title %>", 
                  "duration": "00:50", 
                  "backgroundColor": "var(--<%= subject.color %>)",
                  "borderColor": "var(--<%= subject.color %>)", 
                  "activityable_gid": "<%= GlobalID::Locator.locate(params[:activityable_gid]).to_global_id.uri rescue School.first.to_global_id.uri %>", 
                  "subjectName": "<%= subject.title %>",
                  "subjectIcon": "<%= subject.fa_icon %>",
                  "subjectId": "<%= subject.id %>",
                  "update_url": "<%= subject_url(subject) %>?method=patch",
                  "edit_url": "<%= edit_subject_path(subject) %>"
                  }'>
                  <%= icon(subject.fa_icon, subject.title) %>
                </a>
              <% end %>
            </div>

          <% else %>

            <div class="card bg-gradient-warning mb-0 mt-4">
              <div class="card-body py-4 px-3">
                <div class="text-center">
                  <div class="icon icon-shape bg-white text-warning rounded-circle shadow">
                    <i class="far fa-exclamation-triangle mt--1"></i>
                  </div>
                </div>
                <div class="col">
                  <p class="my-3 text-white">
                    <span class="font-weight-bold"><%= t('.no_current_subjects') %></span><br>
                    <%= t('.please_create_subjects') %>
                  </p>
                  <%= link_to icon('far fa-plus', t('.add_subject')), new_subject_path, class: 'btn btn-secondary btn-block' %>
                </div>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>

    <div class="col-lg-9 col-md-8 col-12">
      <div class="card">
        <!-- Card header -->
        <div class="card-header border-0">
          <div class="row">
            <div class="col-6">
              <h3 class="mb-0" id="fc-card-title"></h3>
            </div>
            <div class="col-6 text-right">
              <%= link_to new_activity_path, class: "btn btn-sm btn-primary btn-round btn-icon", data: { toggle: :tooltip, 'original-title': "#{ t 'general.add'} #{ t 'activerecord.models.activity.one' }" } do %>
                <span class="btn-inner--icon">
                  <i class="fas fa-plus"></i>
                </span>
                <span class="btn-inner--text"><%= t 'general.add' %></span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-body p-0">
          <div id="calendar" class="calendar"></div>
        </div>
        <!-- Card footer -->
        <!-- <div class="card-footer py-4">
          <nav aria-label="...">
            <ul class="pagination justify-content-end mb-0">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">
                  <i class="fa fa-angle-left"></i>
                  <span class="sr-only"><%= t 'general.previous' %></span>
                </a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">2
                  <span class="sr-only">(<%= t 'general.current' %>)</span></a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">3</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">
                  <i class="fa fa-angle-right"></i>
                  <span class="sr-only"><%= t 'general.next' %></span>
                </a>
              </li>
            </ul>
          </nav>
        </div> -->
      </div>

    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

<% content_for(:page_title, "#{ t 'general.list_of' } #{t('activerecord.models.activity.other').titleize}") %>

<script>
  $('.subject-draggable').mousedown(function () {
    $(this).removeClass('cursor-grab');
    $(this).addClass('cursor-grabbing');
  });

  $('.subject-draggable').mouseup(function () {
    $(this).removeClass('cursor-grabbing');
    $(this).addClass('cursor-grab');
  });

  $('.fc-timegrid-event-harness').mousedown(function () { 
    console.log('mousedown')
    $(this).removeClass('cursor-grab');
    $(this).addClass('cursor-grabbing');
  });

  $('.fc-timegrid-event-harness').mouseup(function () { 
    $(this).removeClass('cursor-grabbing');
    $(this).addClass('cursor-grab');
  });
</script>

app/views/activities/index.js.erb
// Get urlParams from current url
var urlParams = new URLSearchParams(window.location.search)
urlParams.set('activityable_gid', '<%= params[:activityable_gid] %>') // set activityableGid to the new gid

// Change the url without reloading the page
var newRelativePathQuery = window.location.pathname + '?' + urlParams.toString()
history.pushState(null, '', newRelativePathQuery)

// Change the Choose activityable button title
$('#dropdownMenuLink').text('<%= GlobalID::Locator.locate(params[:activityable_gid]).name %>')

<% if GlobalID::Locator.locate(params[:activityable_gid]).class.to_s == "Classroom" %>
    $('#dropdownMenuLink').removeClass().addClass('btn btn-<%= GlobalID::Locator.locate(params[:activityable_gid]).color %> dropdown-toggle btn-block')
<% else %>
    $('#dropdownMenuLink').removeClass().addClass('btn btn-primary dropdown-toggle btn-block')
<% end %>

// Rerender the calendar
calendar.render()
calendar.getEventSources().forEach(eventSource => eventSource.refetch())

app/views/activities/new.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.activity.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.activity.other').titleize, activities_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.new' %> <%= t('activerecord.models.activity.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.add_new' %> <%= t('activerecord.models.activity.one') %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', activity: @activity %>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), activities_path, class: 'btn btn-light' %>
</div>

<% content_for(:page_title, "#{t('general.add')} #{t('activerecord.models.activity.one')}") %>

app/views/activities/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");

$('#modal-window').modal('show');

$('#modal-submit').on('click', function() {
  $('#modal-window').modal('hide');
  const event = new Event('modal-closed')
});

app/views/activities/show.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0"><%= t('activerecord.models.activity.other').titleize %></h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to '<i class="far fa-home"></i>'.html_safe, root_path %>
              </li>
              <li class="breadcrumb-item">
                <%= link_to t('activerecord.models.activity.other').titleize, activities_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page"><%= t 'general.new' %> <%= t('activerecord.models.activity.one') %></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.new' %></a>
          <a href="#" class="btn btn-sm btn-neutral"><%= t 'general.filters' %></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6">
  <div class="card">
    <div class="card-header">
      <h3 class="mb-0"><%= t 'general.show' %> Activity</h4>
    </div>
    <div class="card-body">
      <dl class="row">
	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.all_day' %>:</dt>
	      	        <dd class="col-sm-9"><%= t(@activity.all_day) %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.start' %>:</dt>
	      	        <dd class="col-sm-9"><%= l(@activity.start) %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.end' %>:</dt>
	      	        <dd class="col-sm-9"><%= l(@activity.end) %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.days_of_week' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.days_of_week %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.start_time' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.start_time %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.end_time' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.end_time %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.start_recur' %>:</dt>
	      	        <dd class="col-sm-9"><%= l(@activity.start_recur) %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.end_recur' %>:</dt>
	      	        <dd class="col-sm-9"><%= l(@activity.end_recur) %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.title' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.title %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.description' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.description %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.description_staff_only' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.description_staff_only %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.creator_id' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.creator_id %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.coordinator_id' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.coordinator_id %></dd>
	      	    	      <dt class="col-sm-3"><%= t 'activerecord.attributes.activity.subject' %>:</dt>
	      	        <dd class="col-sm-9"><%= @activity.subject %></dd>
	      	          </dl>
    </div>
  </div>
  <%= link_to icon('far fa-arrow-left', t('general.back')), activities_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>
  <%= link_to icon('far fa-edit', t('general.edit')), edit_activity_path(@activity), class: 'btn btn btn-icon icon-left btn-warning' %>
  <%= link_to icon('far fa-trash', t('general.delete')), @activity, class: "btn btn btn-icon icon-left btn-danger", data: { confirm: t('general.are_you_sure_delete'), remote: true }, method: :delete %>
</div>

<% content_for(:page_title, t('general.show') + " Activity") %>

app/views/activities/update.js.erb
calendar.render()
calendar.getEventSources().forEach(eventSource => eventSource.refetch())
$('#modal-window').modal('hide')